server:
  port: 8095
spring:
  cloud:
      stream:
        bindings:
          output:
            destination: file.event
  rabbitmq:
    publisher-confirm-type: simple
  application:
    name: spring-file-service
file:
  source:
    pattern: "*"