server:
  port: 8097
spring:
  application:
    name: file-consumer-sink-2
  cloud:
    function.definition: fileConsumer
    stream:
      bindings:
        fileConsumer-in-0:
          destination: file.event
          group: file-consumer-sink
          consumer:
            concurrency: 1
#            container-type: simple
            container-type: stream
            dlqQuorum:
              enabled: true
#            quorum:
#              enabled: true
      rabbit:
        bindings:
          fileConsumer-in-0:
            consumer:
#              container-type: simple
              container-type: stream
  rabbitmq:
    listener:
      type: stream
#      type: simple
#    stream:
#      host: localhost
file:
  sink:
#    rootDirectory: "/tmp/io/output"
#logging.level:
#  com:
#    rabbitmq:
#      stream: debug
